<?php

/**
 * @file
 * Contains womact_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function womact_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the womact_migrate module.
    case 'help.page.womact_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('D7-&gt;D8 migration for womenactivists.lib.unb.ca') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function womact_migrate_theme() {
  return [
    'womact_migrate' => [
      'render element' => 'children',
    ],
  ];
}
