schemas:
  bootstrap: 8000
  womact_bs3: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost:3085/themes/contrib/bootstrap/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 0
  node_user_picture: 0
logo:
  path: ''
  url: ''
  use_default: 0
region_wells:
  branding: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
table_responsive: '-1'
table: ''
